apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    prod-eng-service: prod-eng-service
  name: prod-eng-service
spec:
  replicas: 1
  selector:
    matchLabels:
      prod-eng-service: prod-eng-service
  template:
    metadata:
      labels:
        prod-eng-service: prod-eng-service
    spec:
      containers:
        - env:
            - name: ENVIRONMENT_NAME
              value: local
            - name: MONGODB_CONECTION_URL
              value: mongodb://root:example@mongo:27017/
          image: robertpoziumschi/prod-eng-img-pipeline:v1.2.0
          name: prod-eng-service
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prod-eng-service: prod-eng-service
  name: prod-eng-service
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    prod-eng-service: prod-eng-service
